version: '3.7'
services:
    db_mysql:
        container_name: db_mysql
        image: mysql
        restart: always
        env_file:
         - .env
        ports:
         - '3306:3306'
        volumes:
         - ./components/mysql_seed/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    app_node:
        container_name: app_node
        depends_on: 
         - db_mysql
        build: .
        restart: always
        ports:
          - 8080:8080 